#!/usr/bin/env bash

set -eu

PLATFORM_FOLDER=.$(grep -oP 'idea.paths.selector=\K[\w\.\d]+' "$HOME"/idea-IU/bin/idea.sh)

mkdir -p \
    "$HOME"/"$PLATFORM_FOLDER" \
    "$HOME"/.gradle \
    "$HOME"/.m2 \
    "$HOME"/.java \
    "$HOME"/IdeaProjects

docker run --rm \
       -v "$HOME"/idea-IU:/root/idea-IU \
       -v "$HOME"/"$PLATFORM_FOLDER":/root/"$PLATFORM_FOLDER" \
       -v "$HOME"/.gradle:/root/.gradle \
       -v "$HOME"/.m2:/root/.m2 \
       -v "$HOME"/.java:/root/.java \
       -v "$HOME"/IdeaProjects:/root/IdeaProjects \
       -v /dev/shm:/dev/shm \
       -p 5900:5900 \
       -p 6080:80 \
       ljishen/docker-vnc-idea-iu
